language: node_js
node_js:
  - "lts/*"

cache: yarn

sudo: true

before_install:
  - gem install bundler
  - gem install danger

before_script:
  - npm install -g yarn
  - node -v
  - yarn -v
  - ruby -v

script:
  - bin/fetch-configlet
  - bin/configlet lint .
  - make report
  - danger
