version: 2

jobs:
  build920:
    macos:
      xcode: "9.2.0"
    steps:
      - run: curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.2/install.sh | bash
      - run: export NVM_DIR="$HOME/.nvm"
      - run: [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
      - run: nvm install --lts
      - run: node -v
      - run: yarn -v
      - checkout
      - run: bin/fetch-configlet
      - run: bin/configlet lint . --track-id=typescript
      - run: touch Brewfile; echo "brew 'gnu-sed'" >> Brewfile;
      - run: brew update
      - run: brew bundle
      - run: gsed -i 's/@sed/@gsed/g;' Makefile
      - run: cat Makefile
      - run: make test

workflows:
  version: 2
  workflow:
    jobs:
      - build920
