version: 2

jobs:
  build920:
    macos:
      xcode: "9.2.0"
    steps:
      - run:
          name: Install node@lts
          command: |
            set +e
            curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.34.0/install.sh | bash
            export NVM_DIR="/opt/circleci/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            nvm install lts
            nvm alias default lts
            echo 'export NVM_DIR="/opt/circleci/.nvm"' >> $BASH_ENV
            echo "[ -s \"$NVM_DIR/nvm.sh\" ] && . \"$NVM_DIR/nvm.sh\"" >> $BASH_ENV
      - run: node -v
      - run: yarn -v
      - checkout
      - run: bin/fetch-configlet
      - run: bin/configlet lint . --track-id=typescript
      - run: touch Brewfile; echo "brew 'gnu-sed'" >> Brewfile;
      - run: brew update
      - run: brew bundle
      - run: gsed -i 's/@sed/@gsed/g;' Makefile
      - run: cat Makefile
      - run: make test

workflows:
  version: 2
  workflow:
    jobs:
      - build920
