name: typescript / format

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout code'
        uses: actions/checkout@24cb9080177205b6e8c946b17badbe402adc938f

      - name: 'Verify formatting of all files'
        run: ./bin/check-formatting.sh
