name: typescript / format

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout code'
        uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3

      - name: 'Verify formatting of all files'
        run: ./bin/check-formatting.sh
